services:
  nginx-demo:
    image: nginx:1.27-alpine
    networks:
      labnet:
        ipv4_address: 172.28.0.40
    ports:
      - "8080:80"
    restart: unless-stopped

  redis-demo:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      labnet:
        ipv4_address: 172.28.0.60
    restart: unless-stopped

  postgres-demo:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    networks:
      labnet:
        ipv4_address: 172.28.0.70
    restart: unless-stopped

  memcached-demo:
    image: memcached:1.6-alpine
    command: ["memcached", "-m", "64"]
    networks:
      labnet:
        ipv4_address: 172.28.0.90
    restart: unless-stopped
